### PR TITLE
Update tsconfig.json to emit jest/browser com...

### LINKED ISSUE #6: Jest: Unexpected token export
I have an Angular application with Jest testing.

If I install SubSink as an npm package (https://www.npmjs.com/package/subsink), my tests fail with the following error:

Jest encountered an unexpected token
SyntaxError: Unexpected token export

As far as I understand, this happens because the package has been transpiled to ES2015 and not ES5. I haven't been able to find a Jests configuration solution.

### PR DESCRIPTION
**Pull request by kgdiem**
...patible output.

Resolves #6

### CODE REVIEW

**Comment by ajaynarang** [comment]
Please merge this PR, I just tried it and working fine. Thanks @kgdiem 

Issue was such a pain tried all possible solution like ignoring transformIgnorePatterns both in global and lib jest config but didn't work..

**Comment by wardbell** [comment]
LGTM, except you neglected to bump the version number, which I will do in subsequent commit

**Comment by wardbell** [comment]
LGTM, except you neglected to bump the version number, which I will do in subsequent commit

**Comment by wardbell** [comment]
Weird. I merged but it said it didn't. Well ... thank you anyway. It's in there.

**Pull request closed without merging**
